'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {chromium}=require('playwright');
const output=path.resolve(process.env.LIUYAO_TEST_OUTPUT||'test-results');fs.mkdirSync(output,{recursive:true});
const checks=[],errors=[];let server,browser;
function check(label,condition){assert.ok(condition,label);checks.push(label);console.log('PASS',label);}
(async()=>{
 server=spawn(process.env.PYTHON||'python3',[path.join(__dirname,'progress_server.py')],{stdio:['ignore','pipe','inherit']});
 const url=await new Promise((resolve,reject)=>{server.stdout.once('data',x=>resolve(x.toString().trim()));server.once('exit',c=>reject(Error('server '+c)));server.once('error',reject);});
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'zh-CN'});page.on('pageerror',e=>errors.push(String(e)));
 await page.addInitScript(()=>{
  delete window.AbortController;
  for(const p of [Element.prototype,Document.prototype,DocumentFragment.prototype])delete p.replaceChildren;
  delete Crypto.prototype.randomUUID;delete Array.prototype.at;delete Object.hasOwn;delete Object.fromEntries;delete Promise.allSettled;
  window.nativeCalls=[];window.LiuyaoAndroid={readPreference:()=>null,savePreference:()=>{},readDraft:()=>localStorage.getItem('test-draft')||'null',saveDraft:x=>localStorage.setItem('test-draft',x),configureModel:()=>{},exportFile:()=>{},analysisState:v=>window.nativeCalls.push(v)};
 });
 await page.route(url+'/',r=>r.continue({headers:{...r.request().headers(),'X-Liuyao-Bootstrap':'progress-test'}}));
 await page.goto(url);await page.waitForFunction(()=>document.querySelector('#model-current').textContent.includes('质量 max'));
 const post=async(endpoint,data)=>{const r=await page.request.post(url+endpoint,{headers:{'X-App-Request':'1','X-Idempotency-Key':'test-'+Date.now()+Math.random()},data});assert.ok(r.ok(),await r.text());return r.json();};
 const control=data=>post('/api/test-control',data);
 const created=await post('/api/cases',{input:{question:'进度界面测试：下个月合同能否签成？',casting:{method:'meibu',results:['1','5','4']},actual_cast_time:'2026-09-19T12:00:00+08:00'}});
 await page.locator('#mobile-history').click();await page.locator('#refresh-history').click();await page.locator('.history-item').first().click();
 const stage=async(name,attempt=1)=>{await page.waitForFunction(({name,attempt})=>document.querySelector('#analysis-stage-'+name).dataset.state==='current'&&(!attempt||document.querySelector('#analysis-progress-text').textContent.includes(attempt===2?'自动修复':'步')),{name,attempt},{timeout:15000});};
 const release=()=>control({release:true});
 await page.locator('#analyze-current-case').click();await stage('intent');
 check('分析开始立即显示当前步骤',await page.locator('#analysis-progress').isVisible());
 check('重新解卦禁用时明确显示分析进行中',await page.locator('#analyze-current-case').isDisabled()&&(await page.locator('#analyze-current-case').textContent()).includes('分析进行中'));
 check('等待时仍可查看回复和刷新状态',await page.locator('#analysis-view-replies').isEnabled()&&await page.locator('#analysis-refresh').isEnabled());
 const caseDetail=await (await page.request.get(url+'/api/cases/'+created.case_id)).json();const jobId=caseDetail.active_job_id;
 let job=await (await page.request.get(url+'/api/jobs/'+jobId)).json();check('任务包含服务时间请求起点和尝试次数',job.server_time&&job.request_started_at&&job.attempt===1&&job.phase==='waiting');
 await page.waitForFunction(()=>/本次已用 [2-9]/.test(document.querySelector('#analysis-elapsed').textContent));
 check('等待期间计时持续变化',true);
 await page.locator('#analysis-view-replies').click();await page.waitForFunction(()=>document.querySelector('#ai-raw-replies-content').textContent.includes('尚未收到完整回复'));
 check('首步未返回时明确说明正在等待正文',await page.locator('#ai-raw-replies').isVisible());
 await page.locator('#analysis-floating').click();check('常驻按钮可返回进度面板',await page.locator('#analysis-progress').isVisible());
 await page.screenshot({path:path.join(output,'waiting.png')});
 await release();await stage('selection');
 check('只按已完成步骤推进进度条',await page.locator('#analysis-stage-progress').evaluate(x=>x.value===1&&x.max===4));
 await page.locator('#analysis-view-replies').click();await page.waitForFunction(()=>document.querySelectorAll('.ai-raw-attempt').length===1);
 check('整次分析未结束即可看到首步实际回复',(await page.locator('.ai-raw-text').textContent()).includes('INTENT_CURRENT'));
 check('回复显示调用耗时和 HTTP 状态',(await page.locator('.ai-raw-attempt').textContent()).includes('HTTP 200'));
 await page.waitForTimeout(350);await page.screenshot({path:path.join(output,'received-reply.png')});
 let before=await control({});await page.locator('#analysis-refresh').click();let after=await control({});check('刷新进度不会新增模型调用',before.calls===after.calls&&before.runs===after.runs);
 await page.route(url+'/api/jobs/*',r=>r.abort('failed'));await page.waitForFunction(()=>document.querySelector('#analysis-connection').textContent.includes('状态连接中断'),null,{timeout:15000});
 check('断线显示最后确认位置且保留进度',await page.locator('#analysis-stage-progress').evaluate(x=>x.value===1));
 await page.locator('#analysis-floating').click();await page.screenshot({path:path.join(output,'disconnected.png')});
 await page.unroute(url+'/api/jobs/*');await page.locator('#analysis-refresh').click();await page.waitForFunction(()=>document.querySelector('#analysis-connection').textContent.includes('本地状态已连接'));
 check('重连继续跟踪原任务',true);
 const held=[];await page.route(url+'/api/jobs/*',r=>{held.push(r);});
 await page.waitForFunction(()=>document.querySelector('#analysis-connection').textContent.includes('12 秒内未响应'),null,{timeout:20000});
 check('状态请求悬停时有超时提示而非永久等待',true);
 await page.unroute(url+'/api/jobs/*');for(const r of held)await r.abort().catch(()=>{});
 await page.locator('#analysis-refresh').click();await page.waitForFunction(()=>document.querySelector('#analysis-connection').textContent.includes('本地状态已连接'));
 before=await control({});await page.reload();await stage('selection');after=await control({});check('重新打开恢复正在运行的任务且不重发',before.runs===after.runs&&before.calls===after.calls);
 await page.locator('#analysis-records-open').click();await page.waitForFunction(()=>document.querySelectorAll('.ai-raw-attempt').length===1);
 check('重新打开仍能查看已返回回复',true);
 await release();await stage('interpretation');await release();await stage('report');
 await page.waitForFunction(()=>!document.querySelector('#analysis-view-answer').hidden);
 check('整理报告期间可提前查看结论',await page.locator('#analysis-view-answer').isEnabled()&&(await page.locator('#analysis-wait-hint').textContent()).includes('90'));
 await page.locator('#analysis-view-answer').click();check('提前结论保留通过校验的解卦答案',(await page.locator('#result-answer').textContent()).includes('签成'));
 await page.locator('#analysis-view-replies').click();await release();
 await page.waitForFunction(()=>document.querySelector('#analysis-progress').dataset.running==='false'&&!document.querySelector('#analyze-current-case').disabled);
 check('结束后恢复重新解卦按钮且停止运行提示',!await page.locator('#analysis-floating').isVisible());
 check('四步完成显示真实完成数',await page.locator('#analysis-stage-progress').evaluate(x=>x.value===4));
 check('回复查看保持展开并更新到全部四步',await page.locator('#ai-raw-replies').getAttribute('open')!==null);
 await page.waitForFunction(()=>document.querySelectorAll('.ai-raw-attempt').length===4);
 check('全部阶段回复与结果均已保存',true);
 check('状态轮询不会反复启动安卓后台通知',await page.evaluate(()=>nativeCalls.filter(Boolean).length===1));
 await control({mode:'fail'});before=await control({});
 await page.route(url+'/api/cases/'+created.case_id+'/analyze',async r=>{await r.fetch();await r.abort();});
 await page.locator('#analyze-current-case').click();await stage('intent');
 await page.unroute(url+'/api/cases/'+created.case_id+'/analyze');after=await control({});
 check('提交回执丢失时恢复已有任务不重复调用',after.runs===before.runs+1&&after.calls===before.calls+1);
 await release();
 await page.waitForFunction(()=>document.querySelector('#analysis-progress').dataset.status==='error'&&!document.querySelector('#analyze-current-case').disabled);
 check('模型错误显示失败步骤和错误代码',(await page.locator('#analysis-job-error').textContent()).includes('authentication_failed')&&(await page.locator('#analysis-progress-text').textContent()).includes('理解问题'));
 await page.locator('#analysis-view-replies').click();await page.waitForFunction(()=>document.querySelector('#ai-raw-replies-content').textContent.includes('HTTP 401'));
 check('调用失败也可查看 HTTP 状态及错误',true);await page.screenshot({path:path.join(output,'provider-error.png')});
 await control({mode:'repair'});await page.locator('#analyze-current-case').click();await stage('intent');await release();await stage('intent',2);
 check('自动修复明确显示为同一步第二次尝试',await page.locator('#analysis-stage-progress').evaluate(x=>x.value===0));
 await page.locator('#analysis-view-replies').click();await page.waitForFunction(()=>document.querySelector('#ai-raw-replies-content').textContent.includes('synthetic invalid JSON'));
 check('修复期间可看未通过校验的原始草稿',true);
 for(const next of ['selection','interpretation','report']){await release();await stage(next);}
 await release();await page.waitForFunction(()=>!document.querySelector('#analyze-current-case').disabled);
 check('自动修复完成后正常解锁',true);
 for(const width of [320,360,390,412]){await page.setViewportSize({width,height:844});check('状态与回复无横向溢出 '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 job=await (await page.request.get(url+'/api/jobs/'+jobId)).json();const again=await(await page.request.get(url+'/api/jobs/'+jobId)).json();check('结束的任务耗时冻结',job.elapsed_seconds===again.elapsed_seconds);
 check('无前端异常',errors.length===0);
 fs.writeFileSync(path.join(output,'browser_results.json'),JSON.stringify({status:'passed',checks,errors,live_api_calls:0,fixture:'真实打包资源和任务服务器，受控合成模型回复'},null,2));
 console.log(JSON.stringify({status:'passed',checks:checks.length}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.kill();});
