'use strict';
const {chromium}=require('playwright'),{spawn}=require('node:child_process');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
let server,browser;
(async()=>{
  server=spawn(process.env.PYTHON||'python3',[path.join(__dirname,'buttons_server.py')],{stdio:['ignore','pipe','inherit']});
  const url=await new Promise((resolve,reject)=>{server.stdout.once('data',b=>resolve(b.toString().trim()));server.once('error',reject);server.once('exit',c=>reject(Error('server '+c)));});
  browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const errors=[];page.on('pageerror',e=>{errors.push(String(e));console.error('PAGE ERROR:',String(e));});page.on('dialog',d=>d.accept());
  await page.addInitScript(()=>{
    window.LiuyaoAndroid={readPreference:()=>null,savePreference:()=>{},readDraft:()=>localStorage.getItem('draft'),saveDraft:s=>localStorage.setItem('draft',s),configureModel:()=>{},exportFile:()=>{},analysisState:()=>{}};
    const nativeRandom=crypto.getRandomValues.bind(crypto);
    window.coinCalls=Number(sessionStorage.getItem('coin-calls')||0);
    Object.defineProperty(crypto,'getRandomValues',{configurable:true,value:target=>{
      if(target.length!==3)return nativeRandom(target);
      if(window.failCoinRandom)throw Error('测试：系统随机数暂不可用');
      const raw=['222','232','332','333','322','323'][window.coinCalls%6];
      target.set(Array.from(raw,v=>v==='2'?254:255));
      window.coinCalls++;sessionStorage.setItem('coin-calls',String(window.coinCalls));return target;
    }});
  });
  await page.route(url+'/',r=>r.continue({headers:{...r.request().headers(),'X-Liuyao-Bootstrap':'button-test'}}));
  await page.goto(url);await page.waitForFunction(()=>Boolean(window.LiuyaoApp));
  await page.locator('#question').fill('随机模拟：六次原始结果保存与恢复');
  await page.locator('#mobile-next').click();
  await page.locator('input[name="casting-method"][value="random_coin"]').check();
  const recommendation=await page.locator('#casting-recommendation').textContent();
  for(const name of ['太极丸','枚卜丸','蓍草','筹策'])assert.ok(recommendation.includes(name));
  for(const width of [320,390,760,1024]){
    await page.setViewportSize({width,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page fits '+width);
    await page.locator('#guide-open').click();
    await page.locator('#random-coin-guide h3').waitFor();
    const text=await page.locator('#random-coin-guide').textContent();
    assert.ok(text.includes('每次三枚')&&text.includes('推荐使用太极丸')&&text.includes('12.5%'));
    assert.ok(!text.includes('暂不提供随机起卦'));
    assert.ok(await page.evaluate(()=>{const d=document.querySelector('#guide-dialog');return d.scrollWidth<=d.clientWidth+1;}),'guide fits '+width);
    await page.locator('#guide-dialog .dialog-close').click();
  }
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>window.coinCalls),0);
  await page.locator('#save-case').click();
  await page.waitForFunction(()=>document.querySelector('#global-message').textContent.includes('第1次随机模拟'));
  // RNG failure does not create a partial token, change the time or use a fallback.
  await page.evaluate(()=>{window.failCoinRandom=true;});
  await page.locator('#random-coin-draw').click();
  assert.match(await page.locator('#random-coin-message').textContent(),/随机数暂不可用/);
  assert.deepEqual(await page.evaluate(()=>window.RandomCoinInput.read()),[null,null,null,null,null,null]);
  assert.equal(await page.locator('#cast-time').inputValue(),'');
  await page.evaluate(()=>{window.failCoinRandom=false;});
  await page.locator('#random-coin-draw').click();
  await page.locator('#random-coin-draw').click();
  const firstTime=await page.locator('#cast-time').inputValue();assert.ok(firstTime);
  assert.deepEqual(await page.evaluate(()=>window.RandomCoinInput.read()),['222','232',null,null,null,null]);
  await page.locator('input[name="casting-method"][value="meibu"]').check();
  await page.locator('input[name="casting-method"][value="random_coin"]').check();
  assert.equal(await page.evaluate(()=>window.coinCalls),2);
  await page.evaluate(()=>window.LiuyaoApp.persistDraft());await page.reload();
  await page.waitForFunction(()=>document.querySelector('#random-coin-1')?.value==='222');
  await page.locator('#mobile-next').click();
  assert.equal(await page.locator('input[name="casting-method"][value="random_coin"]').isChecked(),true);
  assert.equal(await page.locator('#cast-time').inputValue(),firstTime);
  assert.equal(await page.evaluate(()=>window.coinCalls),2);
  await page.locator('#save-case').click();
  await page.waitForFunction(()=>document.querySelector('#global-message').textContent.includes('第3次随机模拟'));
  for(let i=2;i<6;i++)await page.locator('#random-coin-draw').click();
  const raw=['222','232','332','333','322','323'];
  const lines=['old_yin','young_yang','young_yin','old_yang','young_yang','young_yin'];
  assert.deepEqual(await page.evaluate(()=>window.RandomCoinInput.read()),raw);
  assert.deepEqual(await page.evaluate(()=>window.RandomCoinInput.derive(window.RandomCoinInput.read())),lines);
  assert.equal(await page.locator('#random-coin-draw').isDisabled(),true);
  await page.evaluate(()=>document.querySelector('#random-coin-draw').click());
  assert.equal(await page.evaluate(()=>window.coinCalls),6);
  fs.mkdirSync('test-results',{recursive:true});
  await page.locator('#random-coin-inputs').scrollIntoViewIfNeeded();
  await page.screenshot({path:'test-results/random-coin-phone.png'});
  await page.locator('#save-case').click();await page.waitForFunction(()=>document.body.dataset.view==='results');
  const exportUrl=url+await page.locator('#export-case').getAttribute('href');
  const saved=await(await page.request.get(exportUrl)).json();
  assert.deepEqual(saved.original_input.casting,{method:'random_coin',results:raw});
  assert.deepEqual(saved.original_input.lines,lines);
  assert.ok(saved.original_input.actual_cast_time);
  assert.match(await page.locator('#casting-record').textContent(),/随机模拟掷币原始记录.*222 \/ 232 \/ 332/);
  await page.locator('#edit-case-input').click();
  assert.deepEqual(await page.evaluate(()=>window.RandomCoinInput.read()),raw);
  assert.equal(await page.locator('#random-coin-draw').isDisabled(),true);
  assert.equal(await page.evaluate(()=>window.coinCalls),6);
  // Revising only the question must not draw a new hexagram or change provenance.
  await page.locator('.mobile-step-back').click();
  await page.locator('#question').fill('随机模拟：补充问题的时间范围');
  await page.locator('#mobile-next').click();
  await page.locator('#revision-reason').fill('补充所问');
  await page.locator('#save-case').click();await page.waitForFunction(()=>document.body.dataset.view==='results');
  const revised=await(await page.request.get(exportUrl)).json();
  assert.deepEqual(revised.revisions.at(-1).input.casting,{method:'random_coin',results:raw});
  assert.equal(revised.revisions.at(-1).input.actual_cast_time,saved.original_input.actual_cast_time);
  assert.equal(await page.evaluate(()=>window.coinCalls),6);
  await page.locator('#mobile-history').click();await page.locator('#new-case').click();
  assert.deepEqual(await page.evaluate(()=>window.RandomCoinInput.read()),[null,null,null,null,null,null]);
  assert.equal(await page.locator('#cast-time').inputValue(),'');
  assert.deepEqual(errors,[]);
  console.log('PASS: random-coin responsive UI, recommendation and guide, RNG failure, six explicit draws, first time, partial draft restore, source label, export, reopen, revision and new-case reset without rerandomizing.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill();});
